/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PluginsClarityConsentAutoRouteImport } from './routes/plugins.clarity-consent-auto'
import { Route as PluginsSlugRouteImport } from './routes/plugins.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsClarityConsentAutoRoute =
  PluginsClarityConsentAutoRouteImport.update({
    id: '/plugins/clarity-consent-auto',
    path: '/plugins/clarity-consent-auto',
    getParentRoute: () => rootRouteImport,
  } as any)
const PluginsSlugRoute = PluginsSlugRouteImport.update({
  id: '/plugins/$slug',
  path: '/plugins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins/clarity-consent-auto': typeof PluginsClarityConsentAutoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins/clarity-consent-auto': typeof PluginsClarityConsentAutoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins/clarity-consent-auto': typeof PluginsClarityConsentAutoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donate'
    | '/sitemap.xml'
    | '/plugins/$slug'
    | '/plugins/clarity-consent-auto'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/sitemap.xml'
    | '/plugins/$slug'
    | '/plugins/clarity-consent-auto'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donate'
    | '/sitemap.xml'
    | '/plugins/$slug'
    | '/plugins/clarity-consent-auto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PluginsSlugRoute: typeof PluginsSlugRoute
  PluginsClarityConsentAutoRoute: typeof PluginsClarityConsentAutoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/clarity-consent-auto': {
      id: '/plugins/clarity-consent-auto'
      path: '/plugins/clarity-consent-auto'
      fullPath: '/plugins/clarity-consent-auto'
      preLoaderRoute: typeof PluginsClarityConsentAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$slug': {
      id: '/plugins/$slug'
      path: '/plugins/$slug'
      fullPath: '/plugins/$slug'
      preLoaderRoute: typeof PluginsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PluginsSlugRoute: PluginsSlugRoute,
  PluginsClarityConsentAutoRoute: PluginsClarityConsentAutoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
